baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
disableKinds = ['taxonomy', 'term']
defaultColor = "dark"

[params.author]
  avatar = "natsu.png"
  intro = "Deva's Notes"
  name = "Deva Pramod"
  description = "A fast, minimalistic Hugo theme with light and dark mode support, for running a personal site or blog."


[menu]
  [[menu.main]]
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/DevaP11"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/deva-pramod-3200bb216"

[params]
    pageFind = true
